### ISSUE TITLE
Maximize titlebar icon is not centered on some icon sizes

### ISSUE THREAD

**Issue by arttuc** [paulmcauley/klassy#107]
After commit 6a130e5f33901f4d94c8828cf4e70bffa67195d4 the maximize icon is 1px smaller from the top and left sides on icon size 16 and 20.
![kuva](https://github.com/paulmcauley/klassy/assets/37794543/849e4bcc-d53a-4501-afab-d5804eea5368)
Close button also looks shorter and blurrier than usual.

Same configuration on 069599ca7b07b82a017efc0881e0f0be85ed0cb9:
![kuva](https://github.com/paulmcauley/klassy/assets/37794543/c8ae46ad-1b8e-4ccf-b3d4-965e3c936e5c)

Operating System: Arch Linux
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12

Kwin on Wayland

**Comment by paulmcauley** [comment]
You are seeing this because I didn't like the difference in size that was occurring between the minimize and maximize icons, especially on default size 20 with default button shape, therefore sacrificed the centring to fix it.

See 8f650eb0776668530caec18eeff3576a5afe35d9 fix . I have now modified the algorithm so that on low resolution screens and when you use a small circle/square/rounded square button it prioritises the centring. The sizing will be prioritised on the Full-height/integrated buttons as it is not so noticeable that the icon is not centred on these larger buttons (in fact the close button is actually better centred on full-height/integrated).
