### ISSUE TITLE
Background color of the tab close buttons in the application style has changed

### ISSUE THREAD

**Issue by efermi** [paulmcauley/klassy#118]
With the recent release the color got darker and I want to restore it to what it was or to what the default Breeze provides. Is this intentional? Can I restore it?
klassy:
![Screenshot_20240312_185420](https://github.com/paulmcauley/klassy/assets/3966555/b0a7e10e-50eb-43b5-b7b1-f7b5435bfd25)
breeze: 
![Screenshot_20240312_185533](https://github.com/paulmcauley/klassy/assets/3966555/e2fabf5f-e9c2-41dc-821e-d56f8c2ca3fc)

**Comment by paulmcauley** [comment]
I had to make a compromise so that the application style button colours would work with a wide variety of styles, and not just Breeze.

The application style button "titlebar text" colour is taken from a variation of the application Window Text colour, but this is also mixed with Klassy's inactive window button colour settings. You can therefore make a workaround for this by changing the Klassy window decoration inactive button colour opacity setting to 70% (make sure to unlock the active and active button settings first at the top-right):
![breeze_settings](https://github.com/paulmcauley/klassy/assets/6924479/80b3933f-c3dc-4283-8af7-a5201666d874)

Here is also a Window Decoration preset file which does this. I will update the preset for the next release with this if you think that is a good idea:

[Breeze_Original.klpw.zip](https://github.com/paulmcauley/klassy/files/14577912/Breeze_Original.klpw.zip)

Alternatively, if you want things more exactly as Breeze then change 0.7 in the following line to 0.5:
https://github.com/paulmcauley/klassy/blob/3c5480248edcdb674e66f24fe31c014a94e31353/kstyle/breezestyle.cpp#L7972

I might be able to make it exactly the same but it is quite complex and require some thought...

**Comment by efermi** [comment]
Thank you, the workaround is enough for me. Updating the preset is a good idea I think.
