### ISSUE TITLE
Close button icon has changed

### ISSUE THREAD

**Issue by efermi** [paulmcauley/klassy#124]
Compared to 4.3 and Breeze the icon size and color are different in the 5.x releases. Is there a way to keep it identical to breeze?

klassy icon theme:
![Screenshot_20240314_014803](https://github.com/paulmcauley/klassy/assets/3966555/705b026c-f74f-4efa-81ff-ee32c64d8541)
breeze:
![Screenshot_20240314_014823](https://github.com/paulmcauley/klassy/assets/3966555/b0b7f0f2-885a-43b5-ba2a-5b2b904f57de)

**Comment by paulmcauley** [comment]
Yes, there is a simple solution - if you want Breeze icons then you can still use the Breeze icons as your icon theme while still using Klassy window decorations, and just not the Klassy icon theme.

This problem actually quite complex and is caused by Breeze not using the same size of close icon for icon-symbolic and icon non-symbolic. In Klassy I have made them the same size and made them overlay exactly. 

The symbolic icons are used in GTK application titlebars, and if they are a different size like in the Breeze close then they don't look right in the titlebar. They are also used for close buttons in QQC2/Kirigami apps and the symbolic and non-symbolic need to overlay in the same position to look right. 

This means that some icons in the UI look a different size. For square buttons (a superior default IMO) they look perfect, but the circle ones may look different. I have tried to fix this in Breeze a while ago (https://invent.kde.org/frameworks/breeze-icons/-/merge_requests/212 ) but got busty and didn't persevere. Ultimately, I think the best solution is to fix the inconsistent symbolic close icon in Breeze!

**Comment by efermi** [comment]
I agree with your reasoning about the size. Can I somehow affect the color though?

**Comment by paulmcauley** [comment]
> I agree with your reasoning about the size. Can I somehow affect the color though?

You can override any colour in Window Decorations -> Button Colours... -> tick "override individual colours" -> adjust Close Background Hover and Background Press.

I didn't try to match Breeze's colours exactly (actually I don't like them and I think they are actually broken in current Breeze releases cf their original design). In a future release I want to add a "variance" slider under Button Behaviour -> "Vary colours on state change" so that the auto-generated colours can be tuned better.

**Comment by efermi** [comment]
Ah, it wasn't clear what element the icon derives its color from, thank you.

**Comment by paulmcauley** [comment]
There has been a fix to the size on master -- will be available in Klassy 6.7.4
