### ISSUE TITLE
Inactive title bar text not working with some color schemes

### ISSUE THREAD

**Issue by benjamindaines** [paulmcauley/klassy#127]
For whatever reason it seems like inactive title text colors only apply with certain color schemes.  It works with Breeze, for example, as well as others.  However, the color scheme I am trying to use doesn't seem to work with it (https://www.pling.com/p/1669382/).  The color scheme does have an inactive title bar color set.  Why would that be?  Is there a way to make this work, or perhaps to manually set the inactive title text via Klassy? 

Thanks.

**Comment by paulmcauley** [comment]
This is an issue with colour schemes and not with Klassy.

I looked at Mega-Light-Color and the reason why you don't see a different inactive colour is because it uses Header colours, and has only defined an active header text colour and not an inactive one. 

KDE colour schemes are confusing - if you have a "Header" colour set then it will use the header colour and ignore the titlebar colour even if it says a titlebar colour set.

You can edit the colour scheme manually. It has a `[Colors:Header]` section but you also need a `[Colors:Header][Inactive]` section.

**Comment by paulmcauley** [comment]
Closing as not a Klassy issue
