### ISSUE TITLE
Close button's hover outline color (as well as the whole window's) turns white (instead of red) under certain conditions

### ISSUE THREAD

**Issue by LupertEverett** [paulmcauley/klassy#46]
Steps to reproduce:
1. Choose a "dark enough" accent color ("#2c126f" is one such example)
2. Hover on close button:

![Outline](https://user-images.githubusercontent.com/86886753/184551832-35a57692-8374-4b81-86b0-0c3aedd3b534.png)

**Comment by paulmcauley** [comment]
For a proper investigation please provide your full colour scheme from ~/.local/share/color-schemes/ and ~/.config/klassyrc

I doubt the accent colour affects the close button though. There is a contrast detection algorithm which will set the outline colour to the font colour if there is poor contrast between the outline colour and the titlebar/header colour. This works well most of the time but in some cases it doesn't. That's because it is a luma(greyscale)-based contrast detection algorithm from  https://api.kde.org/frameworks/kguiaddons/html/namespaceKColorUtils.html#a9387fe7f2518a87367d9cbc82007994f and probably sees the greyscale values as similar. If you know of a better algorithm let me know.

**Comment by LupertEverett** [comment]
> For a proper investigation please provide your full colour scheme from ~/.local/share/color-schemes/ and ~/.config/klassyrc

Color scheme is the default Breeze Light scheme with the accent color overridden to the color I mentioned above.

klassyrc is [here](https://github.com/paulmcauley/klassy/files/9333974/klassyrc.txt)

Also uploaded a image of what I meant to my initial post, I should've done this earlier, my bad on that.

> If you know of a better algorithm let me know.

I'd say maybe make sure that it always outlines the window and the close button with red when you hover over the close button...? Since the other buttons do not show such behaviour, they always get a color related to the selected accent color.

Though I am not very knowledgeable on that topic, so feel free to ignore what I've said.

**Comment by paulmcauley** [comment]
> Color scheme is the default Breeze Light scheme with the accent color overridden to the color I mentioned above.
It can't be a default Breeze Light. You must also have "Apply accent colour to active window titlebars" ticked.

I can consider making an exception for the close button. Problem is that you wouldn't see the close button if the accent colour was red.

**Comment by LupertEverett** [comment]
> It can't be a default Breeze Light. You must also have "Apply accent colour to active window titlebars" ticked.

Ah, yeah, you're right. I somehow forgot that. My bad once again.

> Problem is that you wouldn't see the close button if the accent colour was red. Or a toggle for Low Contrast Detection -- I will have to think.

Never thought of that, honestly. And had just tried making the accent color full red, and the other buttons got the white outline too, while the close button did the complete opposite lol.
To be honest I think I misunderstood that it could be good for usability, and mistaken the behaviour as a bug.

**Comment by LupertEverett** [comment]
That's good to hear! Thanks!

I haven't been using this for quite a while, should give the new stuff a try soon!
