### ISSUE TITLE
[Request] Option to have translucent background with solid close button

### ISSUE THREAD

**Issue by Dejweed** [paulmcauley/klassy#88]
Hello!
I'm using **background colours** set to **titlebar text color** with **translucent backgrounds** and I would like to have the close button be solid color.

Love the theme, keep up the good work :)

**Comment by Dejweed** [comment]
I would also like the option to always show the icon's background to make it look like libadwaita.

**Comment by paulmcauley** [comment]
These options are now possible on master. Try the "Garden Ornaments" preset.

**Comment by Dejweed** [comment]
I'm still missing translucent colors with solid close button (like Windows 10). 

- Another nice option would be Titlebar text with traffic lights (currently there's only Accent colour with traffic lights)
![image](https://github.com/paulmcauley/klassy/assets/65261588/31b2fbb1-767c-4d52-af18-8682477afc46)

- I think it would be better for presets that use system icons (Rotten Fruits, Windows 11...) to have standard icon sizes (16 or 22 or 24...), so they don't look blurry.
- Would it be possible to merge Button Behaviour with Button Colors and have them together in one place (UI wise)?
- Some presets look different now and should be updated (Windows 10 has solid hover colors). Also what is the difference between Win11 (Cobalt) and Win11 (Win11 icons)? I see one uses accent color while the other doesn't. Could you rename it to make it clearer?

Thank you :)

**Comment by paulmcauley** [comment]
> I'm still missing translucent colors with solid close button (like Windows 10).

You can do this now if you set translucent colours and then set an individual override colour for close. Override colours are going to be extended to also let you select from the palette used as well as just a custom colour. I don't know how to put this in the UI easily any other way. 

>
>     * Another nice option would be Titlebar text with traffic lights (currently there's only Accent colour with traffic lights)
>       ![image](https://private-user-images.githubusercontent.com/65261588/294680072-31b2fbb1-767c-4d52-af18-8682477afc46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NTYxODMsIm5iZiI6MTcwNDU1NTg4MywicGF0aCI6Ii82NTI2MTU4OC8yOTQ2ODAwNzItMzFiMmZiYjEtNzY3Yy00ZDUyLWFmMTgtODY4MjQ3N2FmYzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE1NDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYzAwZWU0MDAwOGYxNjNjMDM1NmY4MjYxYjMxOTgxY2FmYWQ5YzI4YWU0YTcyZjU2MTdmN2ZlMTNmNTUyNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d-Eii8g-rvisVCfOiXka7s4_ou5r6Ta0m-xdV0JFzRY)
> 
>     * Another nice option would be Highlight using Different icon color (so only the icon color changes)
>       ![image](https://private-user-images.githubusercontent.com/65261588/294686472-760c195d-55e4-4f6f-b1d7-f047799da981.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NTYxODMsIm5iZiI6MTcwNDU1NTg4MywicGF0aCI6Ii82NTI2MTU4OC8yOTQ2ODY0NzItNzYwYzE5NWQtNTVlNC00ZjZmLWIxZDctZjA0Nzc5OWRhOTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE1NDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZTViMGJlY2NhYzlhMzMzZjJmMGUyYzM1OWMwY2JkOWU3NTdkNzQ2OGY5ZjVjMjNlNDAyNzViN2RhMGIxZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NhQp72D-6qCya5aoBRlRhoCAjwuYjJ18MwC5ogjs958)


Maybe, but I'm not sure how to put this in the UI. Suggestions welcome... 

> 
>     * I think it would be better for presets that use system icons (Rotten Fruits, Windows 11...) to have standard icon sizes (16 or 22 or 24...), so they don't look blurry.

Yes, I am using HiDPi so don't notice this. Presets are a work-in-progress... 

> 
>     * Would it be possible to merge Button Behaviour with Button Colors and have them together in one place (UI wise)?

Button behaviour is going to be updated to be a table of checkboxes allowing all possible options like below:


                             Icons             Backgrounds                  Outlines      Close Icon     Close Background      Close Outline

Show on press
Show on hover
Show normally


I'm not sure if I want to complicate the UI even more, but I am going to make it that you can have both open at the same time. UI suggestions welcome, if you can think of a way to merge without making it even more complicated. 

>     * Some presets look different now and should be updated (Windows 10 has solid hover colors).

I haven't tweaked the Windows 10 preset yet. If you can perfect it, feel free to upload a preset file. 

 Also what is the difference between Win11 (Cobalt) and Win11 (Win11 icons)? I see one uses accent color while the other doesn't. Could you rename it to make it clearer?

The reason you have two is because you were using an old version from git which stored the preset in your config file. If you started fresh the old one would be deleted. This will resolve itself as presets are going to move to a different configure file to improve performance. 

I also don't think Cobalt is a complete Win11 icon theme. If you can find a better one let me know, otherwise I may have to code one myself :(

**Comment by paulmcauley** [comment]
>     * Another nice option would be Highlight using Different icon color (so only the icon color changes)

For this I was thinking maybe 3 checkboxes:

Highlight method:
Vary colour of background
Vary colour of outline
Vary colour of icon
